CREATE TABLE cat (
  id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  age INT NOT NULL,
  type VARCHAR(32) NOT NULL,
  image_url VARCHAR(4092) NOT NULL,
  gender VARCHAR(8) NOT NULL
);