spring:
  application:
    name: adoption-api
  cloud:
    services:
      registrationMethod: direct
  datasource:
    url: jdbc:h2:mem:adoption-db;DB_CLOSE_DELAY=-1;
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: cloud

server:
  port: 8080
