spring:
  application:
    name: dog-api
  cloud:
    services:
      registrationMethod: direct
  datasource:
    url: jdbc:h2:mem:dog-db;DB_CLOSE_DELAY=-1;
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8082

---
spring:
  config:
    activate:
      on-cloud-platform: cloud_foundry

server:
  port: 8080